### ISSUE TITLE
test transformation in a particular mode?

### ISSUE THREAD

**Issue by magwas** [fgeorges/xspec#75]
I would like to test a template with a mode= parameter.
How should I write the test case?

**Comment by cirulls** [comment]
Hi Árpád,

it's probably better to post this type of questions on our <a href="https://groups.google.com/forum/#!forum/xspec-users" target="_blank">Google Groups</a> and use the issue tracker to flag bugs or implementation questions.

The documentation at https://github.com/expath/xspec/wiki/Writing-Scenarios#matching-scenarios suggests the following:

> The `x:context` element can also have a `mode` attribute that supplies the mode to apply templates in.

 I give you an example. Take this dummy XSLT which I named process-para.xsl. It has two templates, one of which has a test mode:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    exclude-result-prefixes="xs"
    version="2.0">

    <xsl:template match="para" mode="test">
        <p>
            <xsl:value-of select="."/>
        </p>
    </xsl:template>

    <xsl:template match="para">
        <paragraph>
            <xsl:value-of select="."/>
        </paragraph>
    </xsl:template>


</xsl:stylesheet>
```

You can test the template with the mode by supplying the attribute `mode` in the `x:context` element. If you don't provide a mode, the XSpec test will be applied to the default mode (that's the second scenario).

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<x:description xmlns:x="http://www.jenitennison.com/xslt/xspec" stylesheet="transform-para.xsl">

    <x:scenario label="When processing a paragraph in test mode">
        <x:context mode="test">
            <para>dummy paragraph</para>
        </x:context>

        <x:expect label="convert it to a p element">
            <p>dummy paragraph</p>
        </x:expect>

    </x:scenario>

    <x:scenario label="When processing a paragraph in default mode">
        <x:context>
            <para>dummy paragraph</para>
        </x:context>

        <x:expect label="convert it to a paragraph element">
            <paragraph>dummy paragraph</paragraph>
        </x:expect>

    </x:scenario>

</x:description>
```

Hope it helps!

Sandro

**Comment by magwas** [comment]
Thank you.
